
create schema auxilio

create table MUNICIPIO(
 NOME_MUNICIPIO VARCHAR(50),
 UF VARCHAR(2),
 constraint NOME_MUNICIPIO_PK primary key (NOME_MUNICIPIO)
);

create table PARCELA_EXTRA(
 ID SERIAL,
 PAGAMENTO_BLOQUEADO_OU_CANCELADO INT,
 VALOR_DEVOLVIDO_A_UNIAO INT,
 BOLSA_FAMILIA INT,
 CADUN_NAO_BOLSA INT,
 EXTRA_CADUN INT,
 constraint ID_PK primary key (ID)
);

create table PARCELA(
 ID SERIAL,
 NOME_MUNICIPIO VARCHAR(50),
 ANO_DISPONIBILIZACAO INT,
 MES_DISPONIBILIZACAO INT,
 PARCELA_1 INT,
 PARCELA_2 INT,
 PARCELA_3 INT,
 PARCELA_4 INT,
 PARCELA_5 INT,
 PARCELA_6 INT,
 PARCELA_7 INT,
 PARCELA_8 INT,
 PARCELA_9 INT,
 PARCELA_1_VALOR_BENEFICIO INT,
 PARCELA_2_VALOR_BENEFICIO INT,
 PARCELA_3_VALOR_BENEFICIO INT,
 PARCELA_4_VALOR_BENEFICIO INT,
 PARCELA_5_VALOR_BENEFICIO INT,
 PARCELA_6_VALOR_BENEFICIO INT,
 PARCELA_7_VALOR_BENEFICIO INT,
 PARCELA_8_VALOR_BENEFICIO INT,
 PARCELA_9_VALOR_BENEFICIO INT,
 ID_PARCELA_EXTRA INT,
 constraint ID_PARCELA_PK primary key (ID),
 CONSTRAINT NOME_MUNICIPIO_FK FOREIGN KEY (NOME_MUNICIPIO) REFERENCES MUNICIPIO(NOME_MUNICIPIO),
 CONSTRAINT ID_PARCELA_EXTRA_FK FOREIGN KEY (ID_PARCELA_EXTRA) REFERENCES PARCELA_EXTRA(ID)
);

