version: "3"
services:
  db:
    image: postgres
    container_name: "postgres"
    environment:
      - POSTGRES_DB=auxilio_emergencial
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
