
CREATE TABLE RESPONSAVEL(ID serial NOT NULL, NIS VARCHAR(250) NOT NULL, CPF VARCHAR(11) NOT NULL, NOME VARCHAR(250) NOT NULL, PRIMARY KEY (ID));

CREATE TABLE MUNICIPIO(ID serial NOT NULL, CODIGO_MUNICIPIO_IBGE VARCHAR(250) NOT NULL, UF VARCHAR(2) NOT NULL, NOME VARCHAR(250) NOT NULL, PRIMARY KEY (ID));

CREATE TABLE BENEFICIARIO (ID serial NOT NULL, NIS VARCHAR(250) NOT NULL, CPF VARCHAR(11) NOT NULL, NOME VARCHAR(250) NOT NULL, ENQUADRAMENTO VARCHAR(250) NOT NULL, ID_RESPONSAVEL integer REFERENCES RESPONSAVEL (ID), ID_MUNICIPIO integer REFERENCES MUNICIPIO (ID), PRIMARY KEY (ID) );

CREATE TABLE PARCELA(ID serial NOT NULL, OBSERVACAO VARCHAR(250), VALOR NUMERIC NOT NULL, MES_DISPONIBILIZACAO DATE NOT NULL, NUMERO INTEGER NOT NULL, ID_BENEFICIARIO integer NOT NULL REFERENCES BENEFICIARIO (ID), PRIMARY KEY (ID) );
